// Automatically generated by makemoduledefs.py.

#if (MICROPY_PY_ARRAY)
    extern const struct _mp_obj_module_t mp_module_array;
    #define MODULE_DEF_MP_QSTR_ARRAY { MP_ROM_QSTR(MP_QSTR_array), MP_ROM_PTR(&mp_module_array) },
#else
    #define MODULE_DEF_MP_QSTR_ARRAY
#endif

#if (1)
    extern const struct _mp_obj_module_t fll_engine_cmodule;
    #define MODULE_DEF_MP_QSTR_FLLENGINE { MP_ROM_QSTR(MP_QSTR_fllengine), MP_ROM_PTR(&fll_engine_cmodule) },
#else
    #define MODULE_DEF_MP_QSTR_FLLENGINE
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_ARRAY \
    MODULE_DEF_MP_QSTR_FLLENGINE \
// MICROPY_REGISTERED_MODULES
